name: 'Pip package server Configuration'
description: 'Configure pip to pull from from a private package server'
author: 'bobby.ward@inmar.com'
inputs:
  pypi_hostname:
    description: 'Hostname of the pypi server'
    required: true
  pypi_username:
    description: 'Username for the pypi server'
    required: true
  pypi_password:
    description: 'Password for the pypi server'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
